### ISSUE TITLE
Handle null relationship better on eloquent

### ISSUE THREAD

**Issue by kocoten1992** [laravel/ideas#813] opened 2017-09-27 06:54 UTC
```
$computer->cpu->model
```

if cpu is null, access to model will throw

In 5.5, ```optional``` method was introduce, but on eloquent, it should handle it natively (we have higher order message) because if the chain are long, the optional chain doesn't look good:

```
optional(optional($cluster->computer)->cpu)->model
```

Ultimately, it should look like this:
```
$cluster->computer->cpu->model // if any on chain null, null the rest
```

https://gist.github.com/eric1234/7991763

**Comment by sisve** [comment] 2017-09-27 07:18
Would this still work if I did `if($computer->cpu === null) { ... }`?

**Comment by Dylan-DPC** [comment] 2017-09-27 12:32
You can just do `$computer->cpu->model ?? 'foo';`

**Comment by Kyslik** [comment] 2017-09-27 21:21
`optional()` helper is also available.

**Comment by deleugpn** [comment] 2017-09-28 19:08
What about `withDefault()`?

**Comment by Dylan-DPC** [comment] 2017-11-02 17:53
Duplicate of #748

**Closed** 2018-03-13 19:49 UTC
