### ISSUE TITLE
Illuminate\Routing\Route doesn't preserve original parameter after binding substitution

### ISSUE THREAD

**Issue by d3jn** [laravel/ideas#1375] opened 2018-11-02 12:46 UTC
Greetings!

Recently I found a need to access original (raw) route parameter value in controller, but since I utilize binding for this parameter it's already substituted with a resolved one. Resolution logic looked something like this:

```php
Route::bind('poll', function ($sessionCode) {
    return PollSession::where('code', $sessionCode)->firstOrFail()->poll;
});
```

In my controller there was no need for `PollSession` instance, but later on arouse a need to access this `$sessionCode` value.

It got me thinking that it would be a nice touch if route instance would preserve those original parameter values and have them accessible via something like `parametersRaw()` so that no additional steps are required if situation like this shows up. In my opinion it makes sense to be there and doesn't break anything (it could be implemented by creating separate setter for original values and using it in router alongside `setParameters()` - router's `substituteBindings()` one would be left unchanged).

What do you guys think?

**Comment by sisve** [comment] 2018-11-02 13:13
Could you verify if this is a duplicate of https://github.com/laravel/ideas/issues/1260 ?

**Comment by d3jn** [comment] 2018-11-02 13:20
> Could you verify if this is a duplicate of #1260 ?

Yes, it kinda looks like it is, since the problem of retrieving original parameter used in explicit binding was mentioned there, but the author is not very distinct in describing his situation.

**Comment by d3jn** [comment] 2018-11-02 14:28
Duplicate of #1260

**Closed** 2018-11-07 07:55 UTC
