### ISSUE TITLE
UploadedFile::store() uses md5_file() to generate a file name

### ISSUE THREAD

**Issue by jeroennoten** [laravel/ideas#161] opened 2016-08-17 22:12 UTC
A great new addition to Laravel 5.3 is the `UploadedFile::store()`, which also generates a filename. The generated filename is the [MD5 hash of the contents of the file](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Http/UploadedFile.php#L56). So if the same file is uploaded twice, it will overwrite the first one (correct me if I'm wrong). This could be seen as a feature (it saves storage), but I think it is not the right thing to do (imagine modifying the file without changing the name). I would propose something like uniqid() to generate the filename.

**Comment by alexbowers** [comment] 2016-08-17 22:32
It appears that the function is `md5_file` which is a [php function ](http://php.net/manual/en/function.md5-file.php) to get an md5 hash of a file _by_ filename, but not _of_ the filename.

So i think this might be alright

**Comment by JosephSilber** [comment] 2016-08-17 22:35
I agree that an md5 hash is not the best solution.

What if you upload the same file to two records, and then delete one of the records? Presumably you'd have some sort of trigger that also deletes the file. Now the other record will be linking to a non-existent file 😕

**Comment by jeroennoten** [comment] 2016-08-17 22:36
@alexbowers No... it returns the hash of the file contents. I think you're reading it wrong.

"**Calculates the MD5 hash of the file** specified by the filename parameter"

So it means that the file is specified by the filename parameter, not that it calculates the MD5 hash of the filename.

**Comment by alexbowers** [comment] 2016-08-17 22:38
Ah, i misunderstood your question at the top.

**Comment by alexbowers** [comment] 2016-08-17 22:39
@JosephSilber I guess that your code will have to check in the trigger function for if there is another reference to the file. If there isn't, then remove the file.

**Comment by JosephSilber** [comment] 2016-08-18 02:46
Of course there are workarounds. I'm just saying its unexpected.

**Comment by Skysplit** [comment] 2016-08-18 08:02
I think using [tempnam()](https://secure.php.net/manual/en/function.tempnam.php) could solve this problem

**Comment by jeroennoten** [comment] 2016-08-18 08:09
@Skysplit no that will not work on cloud storage disks like S3

**Comment by Skysplit** [comment] 2016-08-18 08:26
@jeroennoten Ah, you're right. I forgot that there could be different storage drivers.

What about appending `Str::random()` result to file name?

**Comment by jeroennoten** [comment] 2016-08-18 09:01
That will not generate a unique name. Better use something like [`uniqid()`](http://php.net/manual/en/function.uniqid.php).

**Comment by franzliedke** [comment] 2016-08-18 09:21
IIRC MD5 also has problems with conflicts that can be generated by appending well-crafted bytes to a known file. I guess that could be abused to overwrite an existing file with a malicious version.. M

**Comment by boynet** [comment] 2016-08-18 18:08
I have multiple projects that involve content uploads to cloud , in the end there is no way to generate unique name without actually checking for existence first(from the file system or db).

uniqid is good base but it's not 100% guarantee to uniqueness

**Comment by jeroennoten** [comment] 2016-08-18 18:10
@boynet You're completely right.

**Comment by LonnyX** [comment] 2016-09-21 11:59
With this way, we should never remove the files from the disks because their are linked with more than once.

GUID seems a approach, no?

**Comment by jstoone** [comment] 2016-11-01 07:22
As @franzliedke, there can be problems with collisions, but php also has a [sha1_file](http://php.net/manual/en/function.sha1-file.php), which might be more suitable collision-wise.

So I propose that it's either:
1. UUID, as implemented by @themsaid
2. sha1_file, for less possible collisions

It could even be possible for the `FilesHelper::hashName()` to default to either UUID or sha1, and have an extra flag to use the other.

If interested I'd gladly create a PR to illustrate the implementation.

**Comment by jeroennoten** [comment] 2016-11-01 07:37
If the same file is uploaded twice, then also `sha1_file()` results in a collision (of course, that is the purpose of hashing).

So the solution should be a generated ID that is 'as unique as possible'.

**Comment by franzliedke** [comment] 2016-11-01 08:28
@jeroennoten Yes, collisions between two files with the same contents are intended, of course. The problem with MD5 is that there are algorithms that allow you to generate files with *different content* that collide with an existing file.

**Comment by jeroennoten** [comment] 2016-11-01 08:42
Yeah that's right, but we want uniqueness for files with the same content as well.

**Comment by jeroennoten** [comment] 2016-11-02 14:32
This is now fixed and merged in PR 16193

**Comment by boynet** [comment] 2016-11-02 14:37
@jeroennoten it's not totally solved just using str_random(32)) still good chance of duplicate...

 in conclusion for any future readers: if you need more than basic usage don't use this method

**Comment by shukshin-ivan** [comment] 2017-12-19 06:14
@boynet  Have you calculated possibility to have the same filename using `str_random(32)`. It is at least `62^32=2e57` if we assume it is truly random. Too small to exist in the Universe.

**Comment by sisve** [comment] 2017-12-19 08:40
@shukshin-ivan Are you arguing to use str_random, which has already been merged in https://github.com/laravel/framework/pull/16193, or are you arguing the chance of any collisions?

**Comment by shukshin-ivan** [comment] 2017-12-19 08:44
The chance of collision in file names of two files in one folder.

**Comment by dereks** [comment] 2018-09-07 18:32
@jeroennoten  @ishukshin 

I believe this bug should be reopened.

To summarize the requirements:

1. Filename must be unique (and not based on file contents, to prevent hash collisions).
2. The filename must not already exist. If the filename already exists, then it should generate a different unique name and check it for existence again.
3. It should be possible to generate a unique filename (that is tested to not exist), but without actually saving a file with that name. This is so we can use the function to generate a new filename, but pass it to other 3rd-party libraries that expect a filename for their own save() function (like the Laravolt Avatar library).
4. All letters in the generated filename should be in lower-case, because some filesystems are case insensitive.
5. Please do not use str_random(), in case the filenames have punctuation or special characters which are hard to work with at the shell or create false file extensions. Using base64 or hex is safest and most compatible.

Simply using a UUID is the best bet. It meets the requirements above, is a known unique key standard, and is supported by other database / key indexing software systems.

**Comment by dereks** [comment] 2018-09-08 23:52
Here is some working example code. But I'm not sure if using the default Storage:: facade is the appropriate thing to do.  What if the user wants to use a specific driver?
```

    public static function newFileUUID($path_prefix = null, $file_suffix = null)
    {
        $path = "";

        while (1) {
            // Break out when an non-existing filename UUID is found.
            $uuid = (string) Uuid::generate(4);
            $path = $path_prefix . $uuid . $file_suffix;

            $exists = Storage::exists($path);
            if (!$exists) {
                break;
            }
        }

        return $path;
    }

```

This example uses the laravel uuid package. 

`composer require "webpatser/laravel-uuid:^3.0"
`

I saw that Faker has a UUID but I wasn't sure if those were valid or just a repeating set.

**Comment by sisve** [comment] 2018-09-09 04:52
@dereks I see no problem using the Storage facade. The way you uses it will make it default to the default disk, but you could as well send in a disk name into the function. (Or perhaps even a Filesystem instance.)

    $exists = Storage::disk($diskName)->exists($path);
    $exists = $filesystem->exists($path);

However, when it comes to the actual application logic, then I see a race condition between calling exists and actually writing to the file. It's minimal with the use of uuid v4, but is probably more prominent with other ways to generate a filename.

I would also like to add another important thing; reproducability for testing. I presume you use ramsey/uuid which allow me to use a custom uuid factory to make sure I get reproducible values. I would like that the final implementation to have this functionality too.

**Comment by themsaid** [comment] 2021-05-10 08:46
Laravel uses `Str::random(40)` now.

**Closed by themsaid** 2021-05-10 08:46 UTC
