### ISSUE TITLE
Introduce deterministic encryption for efficient queries

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/ideas#2580] opened 2021-04-20 09:56 UTC
Currently, Laravel allows encrypted casts in models, to handle encryption of sensitive fields. However, the current encryption algorithm makes it difficult to run queries against encrypted data.

I propose that we introduce [deterministic encryption](https://en.wikipedia.org/wiki/Deterministic_encryption) similar to how [Rails does](https://edgeguides.rubyonrails.org/active_record_encryption.html#deterministic-and-non-deterministic-encryption) to support efficient queries against encrypted data. I would have sent a PR but I'm hesitant to work on this, given my limited knowledge on encryption.

**Comment by themsaid** [comment] 2021-05-10 16:05
duplicate of https://github.com/laravel/ideas/issues/1471

**Closed by themsaid** 2021-05-10 16:05 UTC
