### ISSUE TITLE
Shall we prepend phpdoc before softDeletes trait?

### ISSUE THREAD

**Issue by xiaohuilam** [laravel/ideas#1593] opened 2019-04-09 11:27 UTC
I mean patch [`src/Illuminate/Database/Eloquent/SoftDeletes.php`](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/SoftDeletes.php)
```php
<?php

namespace Illuminate\Database\Eloquent;

trait SoftDeletes
{
    //....
}
```
to

```php
<?php

namespace Illuminate\Database\Eloquent;

/**
 * @method static self|\Illuminate\Database\Eloquent\Builder onlyTrashed()
 * @method static self|\Illuminate\Database\Eloquent\Builder withTrashed()
 * @method static self|\Illuminate\Database\Eloquent\Builder withoutTrashed()
 */
trait SoftDeletes 
{ 
    //...
}
```

so that we can define some annotations to treat an object is a softDeletes model, which contains those methods.

![image](https://user-images.githubusercontent.com/6964962/55796806-6ccb4f80-5afd-11e9-9825-2156a2946b37.png)

Should we?

**Comment by klimov-paul** [comment] 2019-04-11 14:31
I agree with you, although the doc block for these methods is better to written a little different:

```php
/**
 * @method static \Illuminate\Database\Eloquent\Builder|static onlyTrashed()
 * ...
 */
```

However, Laravel team prefer to ignore IDE type-hinting problem over Eloquent and Facades code, claiming it is no their concern and should be solved via external packages like [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper). 
See https://github.com/laravel/framework/pull/26910 for example.

**Comment by mattstauffer** [comment] 2019-04-11 15:20
@klimov-paul Just because someone comments on an issue doesn't mean they're "Laravel team."

**Comment by klimov-paul** [comment] 2019-04-11 15:36
As the issue is closed by Lavavel team without any explanation - I consider the team agrees the comment, otherwise explicit reason should be provided.

**Comment by klimov-paul** [comment] 2019-04-11 15:38
Relates to #1579

**Comment by xiaohuilam** [comment] 2019-04-11 15:41
> @klimov-paul Just because someone comments on an issue doesn't mean they're "Laravel team."

Agree, before this thread issue, I have already PR over two times for phpDoc enhancement commits.

**Comment by klimov-paul** [comment] 2019-04-12 10:16
> before this thread issue, I have already PR over two times for phpDoc enhancement commits.

Than it is simple: open a PR with this changeset - see whether it will be accepted or not. There is no point to keep this issue open.

**Closed** 2019-04-15 19:21 UTC

**Comment by chriskonnertz** [comment] 2019-04-18 14:01
> However, Laravel team prefer to ignore IDE type-hinting problem over Eloquent and Facades code, claiming it is no their concern and should be solved via external packages like [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper).

1. It *is* their concern. 
2. If they say it should be automtically solved by third party scripts, then it is *their* task to add these scripts on their side - it's not the task of someone using Laravel / the Laravel framework.
3. barryvdh/laravel-ide-helper does not always create complete results so recommending to use it is not a  perfect solution, while adding all(!) helper annotations directly to the source would be.

**Comment by mattstauffer** [comment] 2019-04-18 14:26
@chriskonnertz once again... who is this "they" y'all keep talking about? Who *actually* is saying these things? You're holding a lot of opinions here based on what someone (@klimov-paul) said about the "Laravel team" (with no explanation, still, of who that actually is).

The number of people who officially speak for Laravel is *very* small.

In general, it's basically Taylor. He also has employees and a few moderators. When in doubt, look whether the person who's talking actually has any formal connection to Laravel. They often don't. That doesn't make them wrong, but it does make it a mistake to go around quoting someone saying they're "the Laravel team" and then getting grouchy about what they *have* to do for you.

**Comment by chriskonnertz** [comment] 2019-04-18 16:19
@mattstauffer I deliberately commented in a way NOT assuming that previous statments about the opinion of (potential) Laravel officials were right or not: 

> **_If_** they say it

Maybe my wording was not as distinct as I've thought - I'm not a native English speaker.
