### ISSUE TITLE
Blade broken control structure

### ISSUE THREAD

**Issue by saidbakr** [laravel/ideas#522] opened 2017-04-10 00:27 UTC
I have the following view:

```

@if(!isset($embed))
@extends('layouts.main')
 @section('content')
 @endif
 <div id="aja-content"> 
....
```
In the above code the block inside the `if` statement always works regarding-less `if` is evaluated to true or false. 

Laravel 5.4 and PHP 7.1

**Comment by ajcastro** [comment] 2017-04-10 00:34
$embed might be set... isset() will return true if the $embed is set to either true or false.

**Comment by saidbakr** [comment] 2017-04-10 00:51
@ajcastro  Also the following the evaluated:

```
@php($embed = false) 
@if($embed)
@extends('layouts.main')
 @section('content')
 @endif
 <div id="aja-content"> 
....
```

**Comment by saidbakr** [comment] 2017-04-10 01:02
I'd like to mention that it is related with `extends()`

**Comment by deleugpn** [comment] 2017-04-10 21:48
I think extends gets executed regardless of where you put it. After all, you're extending a template, so it should be the first thing executed.

**Comment by Dylan-DPC** [comment] 2017-04-13 06:36
@saidbakr this looks like a bug. Open an issue in laravel/framework repo

**Comment by Garbee** [comment] 2017-04-13 09:23
This isn't a bug. Blade is doing the best it can. This is just bad use of a
template engine.

**Comment by saidbakr** [comment] 2017-04-15 11:41
@Garbee  How could not it a bug? Blade code should follow PHP flow! so:
```
<?php
$x = 5;
$y = 5;
if ($x != $y){
include('file1.php');
}
```
In the above exmple `file1.php` should not be included. If it is not a bug, this is means we declare that Blade has a broken [**control structure**](https://en.wikiversity.org/wiki/Control_structures)

**Comment by Dylan-DPC** [comment] 2017-04-15 12:53
it's not a bug. You are closing the if inside the section. Its a normal HTML scoping issue

**Comment by deleugpn** [comment] 2017-04-15 12:58
Why Blade should follow PHP Flow? If you're extending a template, then the parent template needs to be parsed before the child.

**Comment by saidbakr** [comment] 2017-04-16 15:50
@deleugpn Because `if` comes before extend. I think it is execution priority issue. i.e who should be evaluated first.

**Comment by Dylan-DPC** [comment] 2017-04-16 17:30
@saidbakr no you missed the point completely. Your `if` and `endif` are in 2 different sections if you observe it carefully

**Closed** 2018-03-09 19:16 UTC
