### ISSUE TITLE
Better Eloquent boolean attribute cast 

### ISSUE THREAD

**Issue by matbeard** [laravel/ideas#503] opened 2017-03-31 13:09 UTC
Eloquent's boolean attribute casting could be better.

I'm having to create a mutator for all my boolean fields because the JavaScript framework I'm using sends 'true'/'false' for checkboxes, which are received as strings.

If Eloquent used something like:
`bool = filter_var($value, FILTER_VALIDATE_BOOLEAN);`
this would return TRUE for "1", "true", "on" and "yes". Returns FALSE otherwise.

In the meantime, is there a way I can override the existing boolean attribute cast?

**Comment by skyrpex** [comment] 2017-03-31 13:49
IMO the sooner you fix the value in the process chain, the better. I think you should fix the stringified 'true' / 'false' in JS before sending the AJAX call.

Even the Laravel's validation wouldn't work for 'true' and 'false'...

**Comment by matbeard** [comment] 2017-03-31 14:38
The problem isn't in JS... it sends well-formed booleans, but PHP treats all posted values as strings.

I could possibly convert the booleans to 1/0 before the AJAX call, but that just doesn't seem the best approach.

**Comment by skyrpex** [comment] 2017-03-31 14:52
If you're using jquery, check this: http://stackoverflow.com/questions/7408976/bool-parameter-from-jquery-ajax-received-as-literal-string-false-true-in-php

Even when using post, the data is URL encoded and booleans are lost. If you send JSON data, it'll work as expected.

**Comment by Garbee** [comment] 2017-03-31 20:15
The problem is `'false'` is perfectly valid string input which could equate to a truthy statement somewhere in a codebase. This also has no way of being transferred as a boolean in non-JSON web form submissions.

This, imo, is where developers need to take more care and really think through their stack setup to make this fluent without needing internals to change. There are plenty of viable methods to have this all work easily already. I'm not sure why internals should be changed which could make upgrading larger projects relying on the current behavior more difficult.

**Closed** 2018-03-09 19:14 UTC
